#!/usr/bin/env bash
# ============================================================
# Charlie Development Environment
# Linux Mint setup script
#
# PURPOSE:
#   Rebuild a fresh Linux Mint installation into the basic
#   development environment used for the Charlie project.
#
# IMPORTANT:
#   This is a blueprint for now.
#   We will refine it as we manually build the environment
#   and confirm what actually works.
#
# Repository:
#   https://github.com/mrgarmise/charlie
# ============================================================
set -e
echo
echo "=========================================="
echo " Charlie Development Environment"
echo " Linux Mint Setup"
echo "=========================================="
echo
# ------------------------------------------------------------
# 1. Update the operating system
# ------------------------------------------------------------
echo "Updating package information..."
sudo apt update
echo "Upgrading installed packages..."
sudo apt upgrade -y
# ------------------------------------------------------------
# 2. Basic development tools
# ------------------------------------------------------------
echo "Installing basic development tools..."
sudo apt install -y \
    git \
    curl \
    wget \
    build-essential \
    ca-certificates \
    unzip \
    zip
# ------------------------------------------------------------
# 3. Python development environment
# ------------------------------------------------------------
echo "Installing Python development tools..."
sudo apt install -y \
    python3 \
    python3-pip \
    python3-venv \
    python3-dev
# ------------------------------------------------------------
# 4. SSH
# ------------------------------------------------------------
echo "Installing SSH tools..."
sudo apt install -y \
    openssh-client
# ------------------------------------------------------------
# 5. Raspberry Pi development tools
# ------------------------------------------------------------
echo "Installing Raspberry Pi development tools..."
sudo apt install -y \
    ssh \
    rsync
# ------------------------------------------------------------
# 6. Create Charlie Python virtual environment
# ------------------------------------------------------------
echo "Creating Charlie Python virtual environment..."
if [ ! -d ".venv" ]; then
    python3 -m venv .venv
else
    echo ".venv already exists; leaving it alone."
fi
# ------------------------------------------------------------
# 7. Activate the virtual environment
# ------------------------------------------------------------
echo "Activating Charlie virtual environment..."
source .venv/bin/activate
# ------------------------------------------------------------
# 8. Upgrade Python packaging tools
# ------------------------------------------------------------
echo "Updating Python packaging tools..."
python -m pip install --upgrade pip setuptools wheel
# ------------------------------------------------------------
# 9. Install Charlie Python dependencies
# ------------------------------------------------------------
if [ -f "requirements.txt" ]; then
    echo "Installing Charlie Python dependencies..."
    pip install -r requirements.txt
else
    echo
    echo "No requirements.txt found."
    echo "Skipping Charlie Python dependencies for now."
fi
# ------------------------------------------------------------
# 10. Optional development tools
# ------------------------------------------------------------
echo
echo "Optional development tools can be added here later."
echo
echo "Possible additions:"
echo "  - VS Code"
echo "  - GitHub CLI"
echo "  - mpremote"
echo "  - OpenCV system packages"
echo "  - Raspberry Pi camera tools"
echo "  - VNC client"
echo
# ------------------------------------------------------------
# 11. Git configuration reminder
# ------------------------------------------------------------
echo
echo "=========================================="
echo " Git configuration"
echo "=========================================="
echo
echo "Git is installed."
echo
echo "Configure your identity manually with:"
echo
echo "  git config --global user.name \"Your Name\""
echo "  git config --global user.email \"your@email.com\""
echo
echo "SSH keys are intentionally NOT generated by"
echo "this script yet. We will handle those separately."
echo
# ------------------------------------------------------------
# 12. Completion
# ------------------------------------------------------------
echo
echo "=========================================="
echo " Charlie development environment complete"
echo "=========================================="
echo
echo "Activate the Python environment with:"
echo
echo "  source .venv/bin/activate"
echo
echo "Then check:"
echo
echo "  python --version"
echo "  git --version"
echo
echo "Next steps will be documented as the"
echo "Charlie development environment evolves."
echo